[project]
name = "actuworry"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "fastapi[standard]>=0.116.1",
    "pandas>=2.3.1",
]
